config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :categories do
    resources :articles
  end

  get 'category/:category_id/article/:id/edit/:edit_link', to: 'articles#edit'

end

app/models/Article.rb
class Article < ActiveRecord::Base
  belongs_to :category

  def create_edit_link
    ('a'..'z').to_a.sample(10).join('').succ
  end
end

app/models/Category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_category, only: [:index, :new, :create, :show, :edit, :update]
  before_action :get_article, only: [:show, :edit, :update]
  def index
    @articles = @category.articles
  end

  def new
    @article = Article.new
  end

  def show
  end

  def create
    @article = Article.new(article_params)
    @article.category = @category
    @article.edit_link = @article.create_edit_link
    respond_to do |format|
      if @article.save
        session[:article_id] = @article.id
        format.html {redirect_to [@category, @article]}
      else
        format.html {render :new}
      end
    end
  end

  def edit
    if params[:edit_link]
      valid_link = @article.edit_link == params[:edit_link]
      redirect_to([@category, @article]) unless valid_link
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html {redirect_to [@category, @article]}
      else
        format.html {render :edit}
      end
    end
  end

  private
  def get_category
    @category = Category.find(params[:category_id])
  end

  def get_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :price, :email)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for [@category, @article] do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h3>Edit your <%= @article.title %> post</h3>

<%= render 'form' %>

<%= link_to 'Back', category_article_path %>

app/views/articles/index.html.erb
<h3><%= @category.name %></h3>

<ul>
  <% @articles.each do |article| %>
  <li><%= link_to article.title, category_article_path(@category, article) %></li>
  <% end %>
</ul>

<%= link_to 'All Categories', categories_path %>
<%= link_to 'Create Article', new_category_article_path %>

app/views/articles/new.html.erb
<h3>Create in the <%= @category.name %> category</h3>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/articles/show.html.erb
<% if session[:article_id] %>
<div>
  <h4>Here is your special link:
    <%= link_to "http://localhost:3000/category/#{@category.id}/article/#{@article.id}/edit/#{@article.edit_link}", edit_category_article_path %>
  </h4>
</div>
<%end%>

<h3><%= @article.title %></h3>
<p><%= @article.price %></p>
<p><%= @article.email %></p>
<p><%= @article.body %></p>


<%= link_to @category.name, category_articles_path %>

app/views/categories/index.html.erb
<h1>HEY! Here's your categories!</h1>
<ul>
<% @categories.each do |category| %>
  <li><%=link_to category.name, category_articles_path(category)%></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistJr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Craiglist Jr. 2.1</h1>
<%= yield %>

</body>
</html>